/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['default']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARangePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    BrandMark: typeof import('./components/BrandMark.vue')['default']
    ChatComposer: typeof import('./components/chat/ChatComposer.vue')['default']
    ChatMessageBubble: typeof import('./components/chat/ChatMessageBubble.vue')['default']
    ChatMessageList: typeof import('./components/chat/ChatMessageList.vue')['default']
    ConversationSidebar: typeof import('./components/chat/ConversationSidebar.vue')['default']
    CopyableId: typeof import('./components/CopyableId.vue')['default']
    HubNavCard: typeof import('./components/HubNavCard.vue')['default']
    InfoField: typeof import('./components/InfoField.vue')['default']
    KpiCard: typeof import('./components/KpiCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScopeFields: typeof import('./components/ScopeFields.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    TierBadge: typeof import('./components/TierBadge.vue')['default']
  }
}
